program Autorev;

uses
  Forms,
  IniFile in 'IniFile.pas' {BoxIniFile},
  Login in 'Login.pas' {BoxLogin},
  Menu in 'Menu.pas' {BoxMenu},
  SistemaSobre in 'SistemaSobre.pas' {BoxSobre},
  CadastroUsuario in 'CadastroUsuario.pas' {BoxUsuarios},
  PesquisaGeral in 'PesquisaGeral.pas' {BoxPesquisar},
  OperacoesComprasPecas in 'OperacoesComprasPecas.pas' {BoxComprasPecas},
  Empresas in 'Empresas.pas' {BoxEmpresas},
  CadastroVeiculos in 'CadastroVeiculos.pas' {BoxVeiculos},
  OperacoesPosVenda in 'OperacoesPosVenda.pas' {BoxPosVenda},
  OperacoesVendasPecas in 'OperacoesVendasPecas.pas' {BoxVendasPecas},
  OperacoesVendasVeiculos in 'OperacoesVendasVeiculos.pas' {BoxVendasVeiculos},
  CadastroPecasFabrica in 'CadastroPecasFabrica.pas' {BoxPecasFabrica},
  CadastroConcessionaria in 'CadastroConcessionaria.pas' {BoxConcessionaria},
  CadastroCfop in 'CadastroCfop.pas' {BoxCFOP},
  CadastroPecas in 'CadastroPecas.pas' {BoxPecas},
  CadastroPessoas in 'CadastroPessoas.pas' {BoxPessoas},
  Parametros in 'Parametros.pas' {BoxParametros},
  CadastroTMO in 'CadastroTMO.pas' {BoxTMO},
  OperacoesComprasNovos in 'OperacoesComprasNovos.pas' {BoxComprasNovos},
  OperacoesComprasUsados in 'OperacoesComprasUsados.pas' {BoxComprasUsados},
  OperacoesCompras in 'OperacoesCompras.pas' {BoxCompras},
  Faturamento in 'Faturamento.pas' {BoxFaturamento},
  FaturamentoGarantia in 'FaturamentoGarantia.pas' {BoxFaturamentoGarantia},
  FaturamentoVeiculos in 'FaturamentoVeiculos.pas' {BoxFaturamentoVeiculos},
  FinanceiroBanco in 'FinanceiroBanco.pas' {BoxFinanceiroBanco},
  FinanceiroBancoEntradas in 'FinanceiroBancoEntradas.pas' {BoxFinanceiroBancoEntradas},
  FinanceiroBancoEntradasPedidos in 'FinanceiroBancoEntradasPedidos.pas' {BoxFinanceiroBancoEntradasPedidos},
  FinanceiroCaixaEntradasOutros in 'FinanceiroCaixaEntradasOutros.pas' {BoxFinanceiroCaixaEntradasOutros},
  FinanceiroCaixaEntradasPendencias in 'FinanceiroCaixaEntradasPendencias.pas' {BoxFinanceiroCaixaEntradasPendencias},
  Biblioteca in 'Biblioteca.pas',
  FinanceiroBancoSaidas in 'FinanceiroBancoSaidas.pas' {BoxFinanceiroBancoSaidas},
  FinanceiroCaixaSaidasCombustivel in 'FinanceiroCaixaSaidasCombustivel.pas' {BoxFinanceiroCaixaSaidasCombustivel},
  FinanceiroCaixaSaidasDeposito in 'FinanceiroCaixaSaidasDeposito.pas' {BoxFinanceiroCaixaSaidasDeposito},
  FinanceiroBancoSaidasGerais in 'FinanceiroBancoSaidasGerais.pas' {BoxFinanceiroBancoSaidasGerais},
  FinanceiroCaixa in 'FinanceiroCaixa.pas' {BoxFinanceiroCaixa},
  FinanceiroCaixaSaidas in 'FinanceiroCaixaSaidas.pas' {BoxFinanceiroCaixaSaidas},
  FinanceiroCaixaEntradas in 'FinanceiroCaixaEntradas.pas' {BoxFinanceiroCaixaEntradas},
  FinanceiroBancoSaidasCombustivel in 'FinanceiroBancoSaidasCombustivel.pas' {BoxFinanceiroBancoSaidasCombustivel},
  FinanceiroBancoResumo in 'FinanceiroBancoResumo.pas' {BoxFinanceiroBancoResumo},
  FinanceiroCaixaResumo in 'FinanceiroCaixaResumo.pas' {BoxFinanceiroCaixaResumo},
  FinanceiroBancoEntradasOutros in 'FinanceiroBancoEntradasOutros.pas' {BoxFinanceiroBancoEntradasOutros},
  FinanceiroBancoSaidasCPagar in 'FinanceiroBancoSaidasCPagar.pas' {BoxFinanceiroBancoSaidasCPagar},
  FinanceiroCaixaEntradasCReceber in 'FinanceiroCaixaEntradasCReceber.pas' {BoxFinanceiroCaixaEntradasCreceber},
  FinanceiroBancoEntradasCreceber in 'FinanceiroBancoEntradasCreceber.pas' {BoxFinanceiroBancoEntradasCReceber},
  FinanceiroCaixaEntradasPedidosCheques in 'FinanceiroCaixaEntradasPedidosCheques.pas' {BoxFinanceiroCaixaEntradasPedidosCheques},
  FinanceiroCaixaSaidasTaxas in 'FinanceiroCaixaSaidasTaxas.pas' {BoxFinanceiroCaixaSaidasTaxas},
  FinanceiroCaixaSaidasCPagar in 'FinanceiroCaixaSaidasCPagar.pas' {BoxFinanceiroCaixaSaidasCPagar},
  OperacoesPosVendaPecas in 'OperacoesPosVendaPecas.pas' {BoxPosVendaPecas},
  OperacoesPosVendaServicos in 'OperacoesPosVendaServicos.pas' {BoxPosVendaServicos},
  FaturamentoPecas in 'FaturamentoPecas.pas' {BoxFaturamentoPecas},
  CadastroCategoria in 'CadastroCategoria.pas' {BoxCategoria},
  RelatorioNotasFiscais in 'RelatorioNotasFiscais.pas' {BoxRelatorioNotasFiscais},
  CadastroCPagas in 'CadastroCPagas.pas' {BoxCPagas},
  ClientePagamentos in 'ClientePagamentos.pas' {BoxClientePagamentos},
  ClienteDebito in 'ClienteDebito.pas' {BoxClienteDebito},
  CadastroCrecebid in 'CadastroCrecebid.pas' {BoxCrecebid},
  RelatorioBoletos in 'RelatorioBoletos.pas' {BoxRelatorioBoleto},
  ReemiteCF in 'ReemiteCF.pas' {BoxReemiteCF},
  PrnDOS in 'PrnDOS.pas',
  Leitura in 'Leitura.pas' {BoxLeitura},
  FinanceiroBancoSaidasSaque in 'FinanceiroBancoSaidasSaque.pas' {BoxFinanceiroBancoSaidasSaque},
  FechamentoPedidos in 'FechamentoPedidos.pas' {BoxFechamentoPedidos},
  FinanceiroCaixaEntradasPedidos in 'FinanceiroCaixaEntradasPedidos.pas' {BoxFinanceiroCaixaEntradasPedidos},
  Exportacao in 'Exportacao.pas' {BoxExportacao},
  FinanceiroCaixaEntradasPedidosCaixa in 'FinanceiroCaixaEntradasPedidosCaixa.pas' {BoxFinanceiroCaixaEntradasPedidosCaixa},
  Efuncoes in 'Efuncoes.pas',
  ReemiteNFs in 'ReemiteNFs.pas' {BoxReemiteNFs},
  Tabelas in 'Tabelas.pas' {BoxTabelas},
  DescontoFinanceira in 'DescontoFinanceira.pas' {BoxDescontoFinanceira},
  ecf in 'ecf.pas' {BoxECF},
  Financiamentos in 'Financiamentos.pas' {BoxFinanciamentos},
  FinanceiroCaixaSaidasGerais in 'FinanceiroCaixaSaidasGerais.pas' {BoxFinanceiroCaixaSaidasGerais},
  FinanceiroCaixaEntradasPedidosBoleto in 'FinanceiroCaixaEntradasPedidosBoleto.pas' {BoxFinanceiroCaixaEntradasPedidosBoleto},
  FinanceiroRenegociacao in 'FinanceiroRenegociacao.pas' {BoxFinanceiroRenegociacao},
  FinanceiroRenegociacaoEfetuar in 'FinanceiroRenegociacaoEfetuar.pas' {BoxFinanceiroRenegociacaoEfetuar},
  FinanceiroRenegociacaoConsultar in 'FinanceiroRenegociacaoConsultar.pas' {BoxFinanceiroRenegociacaoConsultar},
  CadastroCreceber in 'CadastroCreceber.pas' {BoxCreceber},
  EmiteCupomFiscal in 'EmiteCupomFiscal.pas' {BoxEmiteCupomFiscal},
  NFE in 'NFE.pas' {BoxNFe},
  FDB in 'FDB.pas' {FDB1},
  NfeGerenciamento in 'NfeGerenciamento.pas' {BoxNFeGerenciamento},
  Relatorios in 'Relatorios.pas' {BoxRelatorios},
  NFeConfiguracoes in 'NFeConfiguracoes.pas' {BoxNFeConfiguracoes},
  ufrmAguardaNFe in 'ufrmAguardaNFe.pas' {frmAguardaNFe},
  CadastroSerieNFs in 'CadastroSerieNFs.pas' {BoxCadastroSerieNFs},
  CadastroCPagar in 'CadastroCPagar.pas' {BoxCPagar},
  RelatoriosGerenciais in 'RelatoriosGerenciais.pas' {BoxRelatoriosGerenciais},
  NFeImobilizado in 'NFeImobilizado.pas' {BoxNFeImobilizado},
  RelatorioRecibo in 'RelatorioRecibo.pas' {BoxRelatorioRecibo},
  NFeCredDebEstoque in 'NFeCredDebEstoque.pas' {BoxNFeCredDebEstoque},
  FaturamentoPosVenda in 'FaturamentoPosVenda.pas' {BoxFaturamentoPosVenda},
  NFeComplementar in 'NFeComplementar.pas' {BoxNFeComplementar},
  NFeDevolucao in 'NFeDevolucao.pas' {BoxNFeDevolucao},
  FinanceiroBancoEntradasDeposito in 'FinanceiroBancoEntradasDeposito.pas' {BoxFinanceiroBancoEntradasDeposito},
  OperacoesComprasPecasImportacao in 'OperacoesComprasPecasImportacao.pas' {BoxComprasPecasImportacao},
  RelatoriosGerenciaisReceitas in 'RelatoriosGerenciaisReceitas.pas' {BoxRelatoriosGerenciaisReceitas},
  RelatoriosGerenciaisDespesas in 'RelatoriosGerenciaisDespesas.pas' {BoxRelatoriosGerenciaisDespesas},
  DevolucaoVeiculos in 'DevolucaoVeiculos.pas' {BoxDevolucaoVeiculos},
  PecasTrocaCodigo in 'PecasTrocaCodigo.pas' {BoxPecasTrocaCodigo},
  OperacoesComprasNovosImportacao in 'OperacoesComprasNovosImportacao.pas' {BoxComprasNovosImportacao},
  Senha in 'Senha.pas' {BoxSenha};

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TBoxLogin, BoxLogin);
  Application.CreateForm(TBoxMenu, BoxMenu);
  Application.CreateForm(TFDB1, FDB1);
  Application.CreateForm(TBoxIniFile, BoxIniFile);
  Application.CreateForm(TBoxComprasNovosImportacao, BoxComprasNovosImportacao);
  Application.CreateForm(TBoxSenha, BoxSenha);
  //  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.

