unit RelatorioAnomalias;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ComCtrls, ExtCtrls, Grids, DBGrids, DB, IBCustomDataSet, StdCtrls,
  Wwdbigrd, Wwdbgrid, DBClient, Provider;

type
  TBoxRelatorioAnomalias = class(TForm)
    Panel1: TPanel;
    StatusBar1: TStatusBar;
    Label1: TLabel;
    DataSourceCaixa: TDataSource;
    tblCaixa: TIBDataSet;
    tblCaixaID_CAIXA: TIntegerField;
    tblCaixaID_CONCESSIONARIA: TIntegerField;
    tblCaixaID_CLIENTES: TIntegerField;
    tblCaixaDOCUMENTO: TIBStringField;
    tblCaixaORIGEM: TIBStringField;
    tblCaixaNATUREZA: TIBStringField;
    tblCaixaFORMA_PAG: TIBStringField;
    tblCaixaDATA_LANCAMENTO: TDateField;
    tblCaixaDATA_RECEBIMENTO: TDateField;
    tblCaixaVALOR: TIBBCDField;
    tblCaixaCONTA: TIBStringField;
    tblCaixaSTATUS: TIBStringField;
    tblCaixaHISTORICO: TIBStringField;
    tblCaixaID_DEPOSITO: TIntegerField;
    tblCaixaJUROS: TIBBCDField;
    tblCaixaSTATUS_BANCO: TIBStringField;
    tblCaixaNOME: TIBStringField;
    DBGrid1: TDBGrid;
    tblCreceber: TIBDataSet;
    tblCreceberID_CRECEBER: TIntegerField;
    tblCreceberID_CONCESSIONARIA: TIntegerField;
    tblCreceberID_CLIENTES: TIntegerField;
    tblCreceberID_AVALISTA: TIntegerField;
    tblCreceberDOCUMENTO: TIBStringField;
    tblCreceberPARCELA: TIBStringField;
    tblCreceberVEZES: TIBStringField;
    tblCreceberORIGEM: TIBStringField;
    tblCreceberCONTA: TIBStringField;
    tblCreceberVENCIMENTO: TDateField;
    tblCreceberVALOR: TIBBCDField;
    tblCreceberEMISSAO: TDateField;
    tblCreceberTOTAL: TIBBCDField;
    tblCreceberPAGAMENTO: TDateField;
    tblCreceberVALOR_PAGO: TIBBCDField;
    tblCreceberBANCO: TIBStringField;
    tblCreceberHISTORICO: TIBStringField;
    tblCreceberSTATUS: TIBStringField;
    tblCreceberID_PEDIDO_VEICULOS: TIntegerField;
    tblCreceberID_FORMA_PAGAMENTO: TIntegerField;
    DataSourceCreceber: TDataSource;
    DBGrid2: TDBGrid;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    Label5: TLabel;
    Label6: TLabel;
    Label7: TLabel;
    tblOrcamentoPecas: TIBDataSet;
    tblOrcamentoPecasID_ORCAMENTO_PECAS: TIntegerField;
    tblOrcamentoPecasID_CLIENTES: TIntegerField;
    tblOrcamentoPecasTOTAL_VENDA: TIBBCDField;
    tblOrcamentoPecasTOTAL_NESTA_VENDA: TIBBCDField;
    tblOrcamentoPecasSTATUS: TIBStringField;
    tblOrcamentoPecasDESCONTO: TIBBCDField;
    tblOrcamentoPecasVALOR_LIQUIDO_VENDA: TIBBCDField;
    tblOrcamentoPecasID_CONCESSIONARIA: TIntegerField;
    tblOrcamentoPecasID_VENDEDOR: TIntegerField;
    tblOrcamentoPecasNUMERO_NOTA_FISCAL: TIntegerField;
    DataSourceOrcamentoPecas: TDataSource;
    tblAtendimento: TIBDataSet;
    tblAtendimentoID_ATENDIMENTO: TIntegerField;
    tblAtendimentoID_CONCESSIONARIA: TIntegerField;
    tblAtendimentoID_CLIENTES: TIntegerField;
    tblAtendimentoID_MECANICO: TIntegerField;
    tblAtendimentoID_CATEGORIA: TIntegerField;
    tblAtendimentoMARCA: TIBStringField;
    tblAtendimentoMODELO: TIBStringField;
    tblAtendimentoANO_FABRICACAO: TIBStringField;
    tblAtendimentoANO_MODELO: TIBStringField;
    tblAtendimentoCHASSI: TIBStringField;
    tblAtendimentoKM: TIntegerField;
    tblAtendimentoDATA_ENTRADA: TDateField;
    tblAtendimentoDATA_SAIDA: TDateField;
    tblAtendimentoORC_OS: TIBStringField;
    tblAtendimentoCOR: TIBStringField;
    tblAtendimentoPLACA: TIBStringField;
    tblAtendimentoSTATUS: TIBStringField;
    tblAtendimentoMEMO: TBlobField;
    tblAtendimentoDESCONTO: TIBBCDField;
    tblAtendimentoTOTAL_PECAS: TIBBCDField;
    tblAtendimentoTOTAL_SERVICOS: TIBBCDField;
    tblAtendimentoTOTAL_PECAS_TABELA: TIBBCDField;
    tblAtendimentoVALOR_LIQUIDO_VENDA: TIBBCDField;
    tblAtendimentoID_ATENDENTE: TIntegerField;
    DataSourceAtendimento: TDataSource;
    tblPedidoVeiculos: TIBDataSet;
    tblPedidoVeiculosID_PEDIDO_VEICULOS: TIntegerField;
    tblPedidoVeiculosID_CONCESSIONARIA: TIntegerField;
    tblPedidoVeiculosID_CLIENTES: TIntegerField;
    tblPedidoVeiculosID_AVALISTA: TIntegerField;
    tblPedidoVeiculosID_VEICULOS: TIntegerField;
    tblPedidoVeiculosCHASSI: TIBStringField;
    tblPedidoVeiculosMARCA: TIBStringField;
    tblPedidoVeiculosANO_MODELO: TIBStringField;
    tblPedidoVeiculosANO_FABRICACAO: TIBStringField;
    tblPedidoVeiculosPLACA: TIBStringField;
    tblPedidoVeiculosVALOR: TIBBCDField;
    tblPedidoVeiculosBASE_COMISSAO: TIBBCDField;
    tblPedidoVeiculosNF: TIBStringField;
    tblPedidoVeiculosDATA_NF: TDateField;
    tblPedidoVeiculosSTATUS: TIBStringField;
    tblPedidoVeiculosID_VENDEDOR: TIntegerField;
    tblPedidoVeiculosID_FINANCEIRA: TIntegerField;
    tblPedidoVeiculosVALOR_DA_VENDA: TIBBCDField;
    tblPedidoVeiculosMODELO: TIBStringField;
    tblPedidoVeiculosVALOR_A_RECEBER: TIBBCDField;
    tblPedidoVeiculosMOTOR: TIBStringField;
    tblPedidoVeiculosID_USUARIO: TIntegerField;
    tblPedidoVeiculosUSUARIO: TIBStringField;
    tblPedidoVeiculosCOR: TIBStringField;
    tblPedidoVeiculosNF_CANCELAMENTO: TIBStringField;
    tblPedidoVeiculosDATA_NF_CANCELAMENTO: TDateField;
    tblPedidoVeiculosVALOR_VIP: TIBBCDField;
    tblPedidoVeiculosVALOR_NORMAL: TIBBCDField;
    tblPedidoVeiculosVALOR_EXCLUSIVO: TIBBCDField;
    tblPedidoVeiculosVALOR_VIP2: TIBBCDField;
    tblPedidoVeiculosVALOR_NORMAL2: TIBBCDField;
    tblPedidoVeiculosVALOR_EXCLUSIVO2: TIBBCDField;
    tblPedidoVeiculosRENAVAM: TIBStringField;
    tblPedidoVeiculosVALOR_TAXAS: TIBBCDField;
    tblPedidoVeiculosID_MODELO_VEICULOS: TIntegerField;
    tblPedidoVeiculosNOME: TIBStringField;
    tblPedidoVeiculosNOMEFINANCEIRA: TIBStringField;
    DataSourcePedidoVeiculos: TDataSource;
    tblPedidoVeiculos2: TIBDataSet;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    IBStringField1: TIBStringField;
    IBStringField2: TIBStringField;
    IBStringField3: TIBStringField;
    IBStringField4: TIBStringField;
    IBStringField5: TIBStringField;
    IBBCDField1: TIBBCDField;
    IBBCDField2: TIBBCDField;
    IBStringField6: TIBStringField;
    DateField1: TDateField;
    IBStringField7: TIBStringField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    IBBCDField3: TIBBCDField;
    IBStringField8: TIBStringField;
    IBBCDField4: TIBBCDField;
    IBStringField9: TIBStringField;
    IntegerField8: TIntegerField;
    IBStringField10: TIBStringField;
    IBStringField11: TIBStringField;
    IBStringField12: TIBStringField;
    DateField2: TDateField;
    IBBCDField5: TIBBCDField;
    IBBCDField6: TIBBCDField;
    IBBCDField7: TIBBCDField;
    IBBCDField8: TIBBCDField;
    IBBCDField9: TIBBCDField;
    IBBCDField10: TIBBCDField;
    IBStringField13: TIBStringField;
    IBBCDField11: TIBBCDField;
    IntegerField9: TIntegerField;
    IBStringField14: TIBStringField;
    IBStringField15: TIBStringField;
    DataSourcePedidoVeiculos2: TDataSource;
    tblCreceber2: TIBDataSet;
    IntegerField10: TIntegerField;
    IntegerField11: TIntegerField;
    IntegerField12: TIntegerField;
    IntegerField13: TIntegerField;
    IBStringField16: TIBStringField;
    IBStringField17: TIBStringField;
    IBStringField18: TIBStringField;
    IBStringField19: TIBStringField;
    IBStringField20: TIBStringField;
    DateField3: TDateField;
    IBBCDField12: TIBBCDField;
    DateField4: TDateField;
    IBBCDField13: TIBBCDField;
    DateField5: TDateField;
    IBBCDField14: TIBBCDField;
    IBStringField21: TIBStringField;
    IBStringField22: TIBStringField;
    IBStringField23: TIBStringField;
    IntegerField14: TIntegerField;
    IntegerField15: TIntegerField;
    DataSourceCreceber2: TDataSource;
    DBGrid3: TDBGrid;
    DataSetProvider1: TDataSetProvider;
    cdsCreceber: TClientDataSet;
    cdsCreceberID_CRECEBER: TIntegerField;
    cdsCreceberID_CONCESSIONARIA: TIntegerField;
    cdsCreceberID_CLIENTES: TIntegerField;
    cdsCreceberID_AVALISTA: TIntegerField;
    cdsCreceberDOCUMENTO: TStringField;
    cdsCreceberPARCELA: TStringField;
    cdsCreceberVEZES: TStringField;
    cdsCreceberORIGEM: TStringField;
    cdsCreceberCONTA: TStringField;
    cdsCreceberVENCIMENTO: TDateField;
    cdsCreceberVALOR: TBCDField;
    cdsCreceberEMISSAO: TDateField;
    cdsCreceberTOTAL: TBCDField;
    cdsCreceberPAGAMENTO: TDateField;
    cdsCreceberVALOR_PAGO: TBCDField;
    cdsCreceberBANCO: TStringField;
    cdsCreceberHISTORICO: TStringField;
    cdsCreceberSTATUS: TStringField;
    cdsCreceberID_PEDIDO_VEICULOS: TIntegerField;
    cdsCreceberID_FORMA_PAGAMENTO: TIntegerField;
    DataSetProvider2: TDataSetProvider;
    cdsCaixa: TClientDataSet;
    DataSetProvider3: TDataSetProvider;
    cdsOrcamentoPecas: TClientDataSet;
    DataSetProvider4: TDataSetProvider;
    cdsPedidoVeiculos: TClientDataSet;
    DataSetProvider5: TDataSetProvider;
    cdsCreceber2: TClientDataSet;
    DataSetProvider6: TDataSetProvider;
    cdsAtendimento: TClientDataSet;
    DataSetProvider7: TDataSetProvider;
    cdsPedidoveiculos2: TClientDataSet;
    DBGrid4: TDBGrid;
    DBGrid5: TDBGrid;
    DBGrid6: TDBGrid;
    DBGrid7: TDBGrid;
    cdsCreceber2ID_CRECEBER: TIntegerField;
    cdsCreceber2ID_CONCESSIONARIA: TIntegerField;
    cdsCreceber2ID_CLIENTES: TIntegerField;
    cdsCreceber2ID_AVALISTA: TIntegerField;
    cdsCreceber2DOCUMENTO: TStringField;
    cdsCreceber2PARCELA: TStringField;
    cdsCreceber2VEZES: TStringField;
    cdsCreceber2ORIGEM: TStringField;
    cdsCreceber2CONTA: TStringField;
    cdsCreceber2VENCIMENTO: TDateField;
    cdsCreceber2VALOR: TBCDField;
    cdsCreceber2EMISSAO: TDateField;
    cdsCreceber2TOTAL: TBCDField;
    cdsCreceber2PAGAMENTO: TDateField;
    cdsCreceber2VALOR_PAGO: TBCDField;
    cdsCreceber2BANCO: TStringField;
    cdsCreceber2HISTORICO: TStringField;
    cdsCreceber2STATUS: TStringField;
    cdsCreceber2ID_PEDIDO_VEICULOS: TIntegerField;
    cdsCreceber2ID_FORMA_PAGAMENTO: TIntegerField;
    cdsCaixaID_CAIXA: TIntegerField;
    cdsCaixaID_CONCESSIONARIA: TIntegerField;
    cdsCaixaID_CLIENTES: TIntegerField;
    cdsCaixaDOCUMENTO: TStringField;
    cdsCaixaORIGEM: TStringField;
    cdsCaixaNATUREZA: TStringField;
    cdsCaixaFORMA_PAG: TStringField;
    cdsCaixaDATA_LANCAMENTO: TDateField;
    cdsCaixaDATA_RECEBIMENTO: TDateField;
    cdsCaixaVALOR: TBCDField;
    cdsCaixaCONTA: TStringField;
    cdsCaixaSTATUS: TStringField;
    cdsCaixaHISTORICO: TStringField;
    cdsCaixaID_DEPOSITO: TIntegerField;
    cdsCaixaJUROS: TBCDField;
    cdsCaixaSTATUS_BANCO: TStringField;
    cdsCaixaNOME: TStringField;
    cdsOrcamentoPecasID_ORCAMENTO_PECAS: TIntegerField;
    cdsOrcamentoPecasID_CLIENTES: TIntegerField;
    cdsOrcamentoPecasTOTAL_VENDA: TBCDField;
    cdsOrcamentoPecasTOTAL_NESTA_VENDA: TBCDField;
    cdsOrcamentoPecasSTATUS: TStringField;
    cdsOrcamentoPecasDESCONTO: TBCDField;
    cdsOrcamentoPecasVALOR_LIQUIDO_VENDA: TBCDField;
    cdsOrcamentoPecasID_CONCESSIONARIA: TIntegerField;
    cdsOrcamentoPecasID_VENDEDOR: TIntegerField;
    cdsOrcamentoPecasNUMERO_NOTA_FISCAL: TIntegerField;
    cdsPedidoVeiculosID_PEDIDO_VEICULOS: TIntegerField;
    cdsPedidoVeiculosID_CONCESSIONARIA: TIntegerField;
    cdsPedidoVeiculosID_CLIENTES: TIntegerField;
    cdsPedidoVeiculosID_AVALISTA: TIntegerField;
    cdsPedidoVeiculosID_VEICULOS: TIntegerField;
    cdsPedidoVeiculosCHASSI: TStringField;
    cdsPedidoVeiculosMARCA: TStringField;
    cdsPedidoVeiculosANO_MODELO: TStringField;
    cdsPedidoVeiculosANO_FABRICACAO: TStringField;
    cdsPedidoVeiculosPLACA: TStringField;
    cdsPedidoVeiculosVALOR: TBCDField;
    cdsPedidoVeiculosBASE_COMISSAO: TBCDField;
    cdsPedidoVeiculosNF: TStringField;
    cdsPedidoVeiculosDATA_NF: TDateField;
    cdsPedidoVeiculosSTATUS: TStringField;
    cdsPedidoVeiculosID_VENDEDOR: TIntegerField;
    cdsPedidoVeiculosID_FINANCEIRA: TIntegerField;
    cdsPedidoVeiculosVALOR_DA_VENDA: TBCDField;
    cdsPedidoVeiculosMODELO: TStringField;
    cdsPedidoVeiculosVALOR_A_RECEBER: TBCDField;
    cdsPedidoVeiculosMOTOR: TStringField;
    cdsPedidoVeiculosID_USUARIO: TIntegerField;
    cdsPedidoVeiculosUSUARIO: TStringField;
    cdsPedidoVeiculosCOR: TStringField;
    cdsPedidoVeiculosNF_CANCELAMENTO: TStringField;
    cdsPedidoVeiculosDATA_NF_CANCELAMENTO: TDateField;
    cdsPedidoVeiculosVALOR_VIP: TBCDField;
    cdsPedidoVeiculosVALOR_NORMAL: TBCDField;
    cdsPedidoVeiculosVALOR_EXCLUSIVO: TBCDField;
    cdsPedidoVeiculosVALOR_VIP2: TBCDField;
    cdsPedidoVeiculosVALOR_NORMAL2: TBCDField;
    cdsPedidoVeiculosVALOR_EXCLUSIVO2: TBCDField;
    cdsPedidoVeiculosRENAVAM: TStringField;
    cdsPedidoVeiculosVALOR_TAXAS: TBCDField;
    cdsPedidoVeiculosID_MODELO_VEICULO: TIntegerField;
    cdsPedidoVeiculosNOME: TStringField;
    cdsPedidoVeiculosNOMEFINANCEIRA: TStringField;
    cdsAtendimentoID_ATENDIMENTO: TIntegerField;
    cdsAtendimentoID_CONCESSIONARIA: TIntegerField;
    cdsAtendimentoID_CLIENTES: TIntegerField;
    cdsAtendimentoID_MECANICO: TIntegerField;
    cdsAtendimentoID_CATEGORIA: TIntegerField;
    cdsAtendimentoMARCA: TStringField;
    cdsAtendimentoMODELO: TStringField;
    cdsAtendimentoANO_FABRICACAO: TStringField;
    cdsAtendimentoANO_MODELO: TStringField;
    cdsAtendimentoCHASSI: TStringField;
    cdsAtendimentoKM: TIntegerField;
    cdsAtendimentoDATA_ENTRADA: TDateField;
    cdsAtendimentoDATA_SAIDA: TDateField;
    cdsAtendimentoORC_OS: TStringField;
    cdsAtendimentoCOR: TStringField;
    cdsAtendimentoPLACA: TStringField;
    cdsAtendimentoSTATUS: TStringField;
    cdsAtendimentoMEMO: TBlobField;
    cdsAtendimentoDESCONTO: TBCDField;
    cdsAtendimentoTOTAL_PECAS: TBCDField;
    cdsAtendimentoTOTAL_SERVICOS: TBCDField;
    cdsAtendimentoTOTAL_PECAS_TABELA: TBCDField;
    cdsAtendimentoVALOR_LIQUIDO_VENDA: TBCDField;
    cdsAtendimentoID_ATENDENTE: TIntegerField;
    cdsPedidoveiculos2ID_PEDIDO_VEICULOS: TIntegerField;
    cdsPedidoveiculos2ID_CONCESSIONARIA: TIntegerField;
    cdsPedidoveiculos2ID_CLIENTES: TIntegerField;
    cdsPedidoveiculos2ID_AVALISTA: TIntegerField;
    cdsPedidoveiculos2ID_VEICULOS: TIntegerField;
    cdsPedidoveiculos2CHASSI: TStringField;
    cdsPedidoveiculos2MARCA: TStringField;
    cdsPedidoveiculos2ANO_MODELO: TStringField;
    cdsPedidoveiculos2ANO_FABRICACAO: TStringField;
    cdsPedidoveiculos2PLACA: TStringField;
    cdsPedidoveiculos2VALOR: TBCDField;
    cdsPedidoveiculos2BASE_COMISSAO: TBCDField;
    cdsPedidoveiculos2NF: TStringField;
    cdsPedidoveiculos2DATA_NF: TDateField;
    cdsPedidoveiculos2STATUS: TStringField;
    cdsPedidoveiculos2ID_VENDEDOR: TIntegerField;
    cdsPedidoveiculos2ID_FINANCEIRA: TIntegerField;
    cdsPedidoveiculos2VALOR_DA_VENDA: TBCDField;
    cdsPedidoveiculos2MODELO: TStringField;
    cdsPedidoveiculos2VALOR_A_RECEBER: TBCDField;
    cdsPedidoveiculos2MOTOR: TStringField;
    cdsPedidoveiculos2ID_USUARIO: TIntegerField;
    cdsPedidoveiculos2USUARIO: TStringField;
    cdsPedidoveiculos2COR: TStringField;
    cdsPedidoveiculos2NF_CANCELAMENTO: TStringField;
    cdsPedidoveiculos2DATA_NF_CANCELAMENTO: TDateField;
    cdsPedidoveiculos2VALOR_VIP: TBCDField;
    cdsPedidoveiculos2VALOR_NORMAL: TBCDField;
    cdsPedidoveiculos2VALOR_EXCLUSIVO: TBCDField;
    cdsPedidoveiculos2VALOR_VIP2: TBCDField;
    cdsPedidoveiculos2VALOR_NORMAL2: TBCDField;
    cdsPedidoveiculos2VALOR_EXCLUSIVO2: TBCDField;
    cdsPedidoveiculos2RENAVAM: TStringField;
    cdsPedidoveiculos2VALOR_TAXAS: TBCDField;
    cdsPedidoveiculos2ID_MODELO_VEICULO: TIntegerField;
    cdsPedidoveiculos2NOME: TStringField;
    cdsPedidoveiculos2NOMEFINANCEIRA: TStringField;
    tblAtendimento2: TIBDataSet;
    DataSetProvider8: TDataSetProvider;
    cdsAtendimento2: TClientDataSet;
    DataSourceAtendimento2: TDataSource;
    DBGrid8: TDBGrid;
    Label8: TLabel;
    tblAtendimento2ID_ATENDIMENTO: TIntegerField;
    tblAtendimento2ID_CONCESSIONARIA: TIntegerField;
    tblAtendimento2ID_CLIENTES: TIntegerField;
    tblAtendimento2ID_MECANICO: TIntegerField;
    tblAtendimento2ID_CATEGORIA: TIntegerField;
    tblAtendimento2MARCA: TIBStringField;
    tblAtendimento2MODELO: TIBStringField;
    tblAtendimento2ANO_FABRICACAO: TIBStringField;
    tblAtendimento2ANO_MODELO: TIBStringField;
    tblAtendimento2CHASSI: TIBStringField;
    tblAtendimento2KM: TIntegerField;
    tblAtendimento2DATA_ENTRADA: TDateField;
    tblAtendimento2DATA_SAIDA: TDateField;
    tblAtendimento2ORC_OS: TIBStringField;
    tblAtendimento2COR: TIBStringField;
    tblAtendimento2PLACA: TIBStringField;
    tblAtendimento2STATUS: TIBStringField;
    tblAtendimento2MEMO: TBlobField;
    tblAtendimento2DESCONTO: TIBBCDField;
    tblAtendimento2TOTAL_PECAS: TIBBCDField;
    tblAtendimento2TOTAL_SERVICOS: TIBBCDField;
    tblAtendimento2TOTAL_PECAS_TABELA: TIBBCDField;
    tblAtendimento2VALOR_LIQUIDO_VENDA: TIBBCDField;
    tblAtendimento2ID_ATENDENTE: TIntegerField;
    cdsAtendimento2ID_ATENDIMENTO: TIntegerField;
    cdsAtendimento2ID_CONCESSIONARIA: TIntegerField;
    cdsAtendimento2ID_CLIENTES: TIntegerField;
    cdsAtendimento2ID_MECANICO: TIntegerField;
    cdsAtendimento2ID_CATEGORIA: TIntegerField;
    cdsAtendimento2MARCA: TStringField;
    cdsAtendimento2MODELO: TStringField;
    cdsAtendimento2ANO_FABRICACAO: TStringField;
    cdsAtendimento2ANO_MODELO: TStringField;
    cdsAtendimento2CHASSI: TStringField;
    cdsAtendimento2KM: TIntegerField;
    cdsAtendimento2DATA_ENTRADA: TDateField;
    cdsAtendimento2DATA_SAIDA: TDateField;
    cdsAtendimento2ORC_OS: TStringField;
    cdsAtendimento2COR: TStringField;
    cdsAtendimento2PLACA: TStringField;
    cdsAtendimento2STATUS: TStringField;
    cdsAtendimento2MEMO: TBlobField;
    cdsAtendimento2DESCONTO: TBCDField;
    cdsAtendimento2TOTAL_PECAS: TBCDField;
    cdsAtendimento2TOTAL_SERVICOS: TBCDField;
    cdsAtendimento2TOTAL_PECAS_TABELA: TBCDField;
    cdsAtendimento2VALOR_LIQUIDO_VENDA: TBCDField;
    cdsAtendimento2ID_ATENDENTE: TIntegerField;
    procedure FormShow(Sender: TObject);
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
    procedure DBGrid2TitleClick(Column: TColumn);
    procedure DBGrid1TitleClick(Column: TColumn);
    procedure DBGrid3TitleClick(Column: TColumn);
    procedure DBGrid4TitleClick(Column: TColumn);
    procedure DBGrid5TitleClick(Column: TColumn);
    procedure DBGrid7TitleClick(Column: TColumn);
    procedure DBGrid6TitleClick(Column: TColumn);
    procedure DBGrid8TitleClick(Column: TColumn);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  BoxRelatorioAnomalias: TBoxRelatorioAnomalias;

implementation

{$R *.dfm}

procedure TBoxRelatorioAnomalias.DBGrid1TitleClick(Column: TColumn);
begin
   cdsCaixa.IndexFieldNames := Column.FieldName;
   cdsCaixa.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid2TitleClick(Column: TColumn);
begin
   cdsCreceber.IndexFieldNames := Column.FieldName;
   cdsCreceber.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid3TitleClick(Column: TColumn);
begin
   cdsCreceber2.IndexFieldNames := Column.FieldName;
   cdsCreceber2.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid4TitleClick(Column: TColumn);
begin
   cdsOrcamentoPecas.IndexFieldNames := Column.FieldName;
   cdsOrcamentoPecas.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid5TitleClick(Column: TColumn);
begin
   cdsAtendimento.IndexFieldNames := Column.FieldName;
   cdsAtendimento.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid6TitleClick(Column: TColumn);
begin
   cdsPedidoVeiculos.IndexFieldNames := Column.FieldName;
   cdsPedidoVeiculos.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid7TitleClick(Column: TColumn);
begin
   cdsPedidoVeiculos2.IndexFieldNames := Column.FieldName;
   cdsPedidoVeiculos2.First;
end;

procedure TBoxRelatorioAnomalias.DBGrid8TitleClick(Column: TColumn);
begin
   cdsAtendimento2.IndexFieldNames := Column.FieldName;
   cdsAtendimento2.First;
end;

procedure TBoxRelatorioAnomalias.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  DataSourceCreceber.Dataset.Close;
  DataSourceCreceber2.Dataset.Close;
  DataSourcePedidoVeiculos.Dataset.Close;
  DataSourcePedidoVeiculos2.Dataset.Close;
  DataSourceCaixa.Dataset.Close;
  DataSourceOrcamentoPecas.Dataset.Close;
  DataSourceAtendimento.Dataset.Close;
  DataSourceAtendimento2.Dataset.Close;
end;

procedure TBoxRelatorioAnomalias.FormShow(Sender: TObject);
begin
  DataSourceCreceber.Dataset.Open;
  DataSourceCreceber2.Dataset.Open;
  DataSourcePedidoVeiculos.Dataset.Open;
  DataSourcePedidoVeiculos2.Dataset.Open;
  DataSourceCaixa.Dataset.Open;
  DataSourceOrcamentoPecas.Dataset.Open;
  DataSourceAtendimento.Dataset.Open;
  DataSourceAtendimento2.Dataset.Open;
end;

end.

